### ISSUE TITLE
Build initial project structure for React + typescript

### ISSUE THREAD

**Issue by jameshuber15** [steven-pereira/2048-game#6]
Build the initial project structure for the 2048 game. 

We will be using the React framework with Typescript and Sass.

**Comment by steven-pereira** [comment]
Love it man!

**Comment by steven-pereira** [comment]
Do you think we should have the front-end as it's own project so that the API and UI are independent app components that can be deployed in their own containers? Or do you think we shouldn't worry about that right now and keep there together?

**Comment by jameshuber15** [comment]
I don't think we should worry right now. We could always move it around. Plus we don't even have the api setup, this is more just the react and Java version of the same game
